-- ============================================================================
-- Atualiza ee_apoio (prof_manha, prof_tarde, apoios/ASSEJ) a partir da planilha.
-- Mapeamento: Periodo Manha -> prof_manha; Periodo Tarde -> prof_tarde;
--             "SOLUCOES" (col E) -> apoios (ASSEJ).
-- 111 escolas casadas pelo nome exato do banco. Rode no SQL Editor do Supabase.
-- (Sebastiao DE Aguiar Azevedo, EMEF - Un. II nao esta na planilha -> nao alterado.)
-- ============================================================================
update public.ee_apoio a
   set prof_manha = v.pm, prof_tarde = v.pt, apoios = v.ap
  from (values
  ('Alcina dos Santos Heck, EMEF', 2, 3, 2),
  ('Alfeu Luiz Gasparini, Profº., EMEF', 10, 8, 7),
  ('Antonio Palocci, EMEF', 7, 4, 4),
  ('Anisio Teixeira, Profº., EMEF', 6, 5, 4),
  ('Dercy Celia Seixas Ferrari, Profª., EMEF', 4, 4, 3),
  ('Domingos Adilson Canesin, EMEF', 4, 4, 2),
  ('Domingos Angerami, Profº., EMEF', 4, 4, 3),
  ('Eduardo Romualdo DE Souza, Profº., EMEF', 6, 7, 5),
  ('Elisa Duboc Garcia, Profª., EMEF', 4, 4, 3),
  ('Eneida Pereira dos Santos, EMEF', 4, 3, 3),
  ('Eponina DE Britto Rosseto, Profª., EMEF', 2, 2, 2),
  ('Faustino Jarruche, EMEF', 5, 5, 4),
  ('Geralda DE Souza Espin, EMEF', 5, 3, 4),
  ('Honorato DE Lucca, Profº., EMEF', 3, 3, 3),
  ('Jaime Monteiro DE Barros Dr., EMEF', 5, 5, 4),
  ('Jarbas Massulo, Profº., EMEF', 2, 4, 3),
  ('Joao Gilberto Sampaio, Dr., EMEF', 4, 4, 4),
  ('Jose Delibo, Ver., EMEF', 6, 3, 3),
  ('Jose Rodini Luiz Profº., EMEF', 4, 3, 3),
  ('Julio Cesar Voltarelli, DR, EMEF', 3, 6, 4),
  ('Luis DO Amaral Mousinho, Dom, EMEF', 7, 3, 5),
  ('Maria Ignez Lopes Rossi, Profª., EMEF', 3, 5, 3),
  ('Maria Ines Vieira Machado, Profª., EMEF', 4, 3, 3),
  ('Nelson Machado, EMEF', 5, 7, 4),
  ('Neuza Michelutti Marzola, Profª., EMEF', 6, 6, 5),
  ('Paulo Freire, Profº., EMEF', 8, 3, 4),
  ('Paulo Monte Serrat Filho, Profº., Dr., EMEF', 6, 4, 3),
  ('Raul Machado, Profº., EMEF', 7, 6, 3),
  ('Salvador Marturano, Profº., EMEF', 2, 5, 4),
  ('Sebastiao DE Aguiar Azevedo, EMEF', 4, 3, 5),
  ('Sebastiao DE Aguiar Azevedo, EMEF', 2, 4, 3),
  ('Virgilio Salata, EMEF', 11, 8, 6),
  ('Waldemar Roberto, Prof.,dr., EMEF', 5, 3, 5),
  ('Egydio Pedreschi Ceeef', 3, 4, 8),
  ('Adriana Coutinho Brandani Camilo, EMEI', 1, 1, 3),
  ('Albert Einstein, EMEI', 1, 1, 3),
  ('Aloizio Olaia Paschoal, EMEI', 2, 2, 6),
  ('Amelia Junqueira, EMEI', 4, 4, 4),
  ('Amelia Sofia R. DA Costa, Profª., EMEI', 1, 1, 2),
  ('Ana dos Santos Gabarra, EMEI', 2, 2, 4),
  ('Anita Procopio Junqueira, EMEI', 1, 2, 5),
  ('Aurea Aparecida Braghetto Machado, EMEI', 2, 0, 4),
  ('Caetana Spinelli Martins, EMEI', 1, 1, 2),
  ('Carmem Massarotto, Profª., EMEI', 2, 2, 2),
  ('Carmen Aparecida DE Carvalho Ramos, EMEI', 2, 2, 4),
  ('Elza Guazzeli DA Costa, Profª, EMEI', 2, 1, 2),
  ('Emilio Jarbinet, Padre, EMEI', 2, 2, 4),
  ('Henilla Godoy Velludo Salvador, EMEI', 3, 1, 3),
  ('Hilda Maria Sobral Barbosa Mandarino, EMEI', 2, 2, 4),
  ('Hilda Mosca, EMEI', 2, 1, 4),
  ('Iria Junqueira, Dona, EMEI', 1, 2, 4),
  ('Joao Sperandio, Dep., EMEI', 2, 1, 4),
  ('Jose Bonifacio Coutinho Nogueira, EMEI', 1, 1, 5),
  ('Jose Carlos Sobral, Dr., EMEI', 2, 2, 4),
  ('Jose Pedro Moreira, Profº., EMEI', 3, 4, 5),
  ('Jose Roberto Felicio, EMEI', 2, 0, 2),
  ('Lilian Spadaro Rosa E Silva, Profª., EMEI', 1, 1, 3),
  ('Maria Apparecida Borges DE O. Bonini, EMEI', 1, 2, 5),
  ('Maria Goretti, Santa, EMEI', 3, 3, 3),
  ('Maria Helena Braga Monte Serrat, EMEI', 2, 1, 3),
  ('Maria Pontim, EMEI', 1, 1, 4),
  ('Marlene Jorge dos Reis, EMEI', 3, 1, 4),
  ('Miguel Mussi, EMEI', 2, 2, 4),
  ('Moacir Firmino, EMEI', 3, 1, 3),
  ('Narciso Nicolodi, Irmão, EMEI', 2, 1, 4),
  ('Neide Apparecida Golfetto DE Castro, EMEI', 1, 1, 3),
  ('Nicolau Dinamarco Spinelli, Dr., EMEI', 2, 1, 5),
  ('Paulo Henrique DE Souza, EMEI', 2, 1, 2),
  ('Roberto Afonso Pontes, EMEI', 1, 1, 2),
  ('Ruy Escorel Ferreira Santos, EMEI', 2, 2, 4),
  ('Terezinha, Santa, EMEI', 1, 1, 3),
  ('Teresa Hendrica Antonissen, EMEI', 3, 3, 4),
  ('Wanda Princivalli Marcal, EMEI', 2, 2, 4),
  ('Wilson Roselino, EMEI', 2, 0, 4),
  ('Zilda Cossa D Avila, EMEI', 2, 2, 3),
  ('Alaor Galvao Cesar, CEI', 0, 0, 4),
  ('Ana Franco DO Amaral, Prof., CEI', 0, 0, 5),
  ('Ana Maria Chufalo, CEI', 0, 0, 4),
  ('Anna Augusta França, CEI', 0, 0, 4),
  ('Anna Ignes Carvalho Gouvea, CEI', 0, 0, 3),
  ('Aurelio Pacagnella, CEI', 0, 0, 3),
  ('Branca Serra, CEI', 0, 0, 3),
  ('Cecilio Fraguas, CEI', 0, 0, 3),
  ('Cloresdith Ferlin Ferreira, CEI', 0, 0, 5),
  ('Deolinda Gasparini, CEI', 0, 0, 6),
  ('Dom Bosco, CEI', 0, 0, 3),
  ('Felicita Drudi Costa Pinto, CEI', 0, 0, 4),
  ('Girassol Encantado, CEI', 0, 0, 3),
  ('Hortencio Pereira DA Silva, Prof, CEI', 0, 0, 5),
  ('Jesus DE Nazare, CEI', 0, 0, 3),
  ('Joao DA Cruz Moreira, CEI', 0, 0, 4),
  ('Joao Pedro Castroviejo, CEI', 0, 0, 6),
  ('Laurivaldo Fidelis, CEI', 0, 0, 3),
  ('Leonor Mertília Costa, CEI', 0, 0, 5),
  ('Lucio Mendes, CEI', 0, 0, 4),
  ('Maria DE Lourdes Gullaci Laguna Profa, CEI', 0, 0, 4),
  ('Maria Lucia Meirelles Junqueira, CEI', 0, 0, 3),
  ('Maria Regina Cavalcante, Profa, CEI', 0, 0, 5),
  ('Marlene Marreiro Sibille, CEI', 0, 0, 3),
  ('Modelo Marincek, CEI', 0, 0, 5),
  ('Nair Manoelina DE Oliveira, CEI', 0, 0, 5),
  ('Nelson Costa dos Santos, Padre, CEI', 0, 0, 3),
  ('Opus Dei, CEI', 0, 0, 4),
  ('Quintino Vieira, CEI', 0, 0, 5),
  ('Renato Camargo Mendes, CEI', 0, 0, 4),
  ('Roberto Taranto, CEI', 0, 0, 3),
  ('Rosa Maria DE Britto Cosenza, CEI', 0, 0, 3),
  ('Sebastiao Martins DE Moura, CEI', 0, 0, 4),
  ('Thomaz Urbinatti, CEI', 0, 0, 3),
  ('Tony Miyasaka, CEI', 0, 0, 4),
  ('Vitor Youssef Darkoubi, CEI', 0, 0, 4)
  ) as v(escola, pm, pt, ap)
 where a.escola = v.escola;

-- Conferencia pos-update (totais esperados: manha=240, tarde=210, assej=420):
-- select coalesce(sum(prof_manha),0) m, coalesce(sum(prof_tarde),0) t, coalesce(sum(apoios),0) a from public.ee_apoio;
