-- ============================================================================
-- Gestores e Coordenadores (liberação de acesso, igual às escolas).
-- Gerado da planilha "MAPA - Usuarios.csv". 168 perfis.
-- Cada perfil é vinculado à sua unidade -> acessa todas as telas (exceto
-- relatorios/boletim) com dados isolados na unidade. Idempotente.
-- Pré-requisito: sql/07,08,12 (norm_escola), 20. Rode depois deles.
-- ============================================================================
-- Temp de SESSÃO (sem "on commit drop" e sem begin/commit): o SQL Editor do
-- Supabase confirma cada statement, então a temp precisa sobreviver entre eles.
drop table if exists _imp;
create temp table _imp (email text, nome text, escola text, vinculo text);
insert into _imp (email, nome, escola, vinculo) values
    ('jacquelineiossi@educacao.pmrp.sp.gov.br','JACQUELINE PISCHIOTTIN IOSSI','ADRIANA COUTINHO BRANDANI CAMILO, EMEI','gestor'),
    ('dianenilson@educacao.pmrp.sp.gov.br','DIANE RODRIGUES NILSON','ALAOR GALVAO CESAR CEI','gestor'),
    ('marinasantos@educacao.pmrp.sp.gov.br','MARINA APARECIDA CAMARA SAIANI DA MOTA E SANTOS','ALBERT EINSTEIN, EMEI','gestor'),
    ('kelinardi@educacao.pmrp.sp.gov.br','KELI BENTO BARROS NARDI','ALCINA DOS SANTOS HECK, EMEF','gestor'),
    ('danubiasantos@educacao.pmrp.sp.gov.br','DANUBIA CAROLINE DOS SANTOS','ALCINA DOS SANTOS HECK, EMEF','gestor'),
    ('renatabatista@educacao.pmrp.sp.gov.br','RENATA DA SILVA REGO','ALCINA DOS SANTOS HECK, EMEF','coordenador'),
    ('adiltonlima@educacao.pmrp.sp.gov.br','ADILTON DIAS LIMA','ALFEU LUIZ GASPARINI, PROFº., EMEF','gestor'),
    ('cibelepereira@educacao.pmrp.sp.gov.br','CIBELE ZANATTA DA SILVA PEREIRA','ALFEU LUIZ GASPARINI, PROFº., EMEF','gestor'),
    ('adrianagodoy@educacao.pmrp.sp.gov.br','ADRIANA CRISTINA DE GODOY','ALFEU LUIZ GASPARINI, PROFº., EMEF','coordenador'),
    ('daniloalves@educacao.pmrp.sp.gov.br','DANILO EPIPHANEO ALVES','ALOIZIO OLAIA PASCHOAL, EMEI','gestor'),
    ('rosemeirefrancisco@educacao.pmrp.sp.gov.br','ROSEMEIRE CEZARIO FRANCISCO','AMELIA JUNQUEIRA, EMEI','gestor'),
    ('danielladovicchi@educacao.pmrp.sp.gov.br','DANIELLA PATRICIA ALVES DOVICCHI','AMELIA SOFIA RODRIGUES DA COSTA, PROFª., EMEI','gestor'),
    ('mariaanjos@educacao.pmrp.sp.gov.br','MARIA LUCIA FERNANDES CAMILO DOS ANJOS','ANA DOS SANTOS GABARRA, EMEI','gestor'),
    ('andregoulart@educacao.pmrp.sp.gov.br','ANDRE LUIS DE SOUZA GOULART','ANA FRANCO DO AMARAL PROF. CEI','gestor'),
    ('renatapinto@educacao.pmrp.sp.gov.br','RENATA PAULINO PINTO','ANA MARIA CHUFALO CEI','gestor'),
    ('lidiaporto@educacao.pmrp.sp.gov.br','LIDIA LYRA CORDEIRO PORTO','ANISIO TEIXEIRA, PROFº., EMEF','gestor'),
    ('eulaliafabiano@educacao.pmrp.sp.gov.br','EULALIA FABIANO','ANISIO TEIXEIRA, PROFº., EMEF','gestor'),
    ('franciscaconstantino@educacao.pmrp.sp.gov.br','FRANCISCA DE LIMA CONSTANTINO','ANISIO TEIXEIRA, PROFº., EMEF','coordenador'),
    ('samuelpinto@educacao.pmrp.sp.gov.br','SAMUEL RODRIGUES PINTO','ANITA PROCOPIO JUNQUEIRA, EMEI','gestor'),
    ('camilalemes@educacao.pmrp.sp.gov.br','CAMILA LEMES DA COSTA FREITAS','ANNA AUGUSTA FRANÇA CEI','gestor'),
    ('joelpereira@educacao.pmrp.sp.gov.br','JOEL LUIZ PEREIRA','ANNA IGNES CARVALHO GOUVEA CEI','gestor'),
    ('mdsilva@educacao.pmrp.sp.gov.br','MARCIO DA SILVA','ANTONIO PALOCCI, EMEF','gestor'),
    ('felipebazeio@educacao.pmrp.sp.gov.br','FELIPE SOUZA BAZEIO','ANTONIO PALOCCI, EMEF','gestor'),
    ('lucianaprevatti@educacao.pmrp.sp.gov.br','LUCIANA DAVID PREVATTI','ANTONIO PALOCCI, EMEF','coordenador'),
    ('cintiasilverio@educacao.pmrp.sp.gov.br','CINTIA CLAUDINO SILVERIO','AUREA APPARECIDA BRAGHETTO MACHADO, EMEI','gestor'),
    ('nilmaraspressola@educacao.pmrp.sp.gov.br','NILMARA HELENA SPRESSOLA','AURELIO PACAGNELLA CEI','gestor'),
    ('sandrazanella@educacao.pmrp.sp.gov.br','SANDRA DOS REIS COELHO ZANELLA','BRANCA SERRA CEI','gestor'),
    ('dayanabittar@educacao.pmrp.sp.gov.br','DAYANA BORGES BITTAR','CAETANA SPINELLI MARTINS, EMEI','gestor'),
    ('marianaluppi@educacao.pmrp.sp.gov.br','MARIANA CARVALHO LUPPI','CARMEM MASSAROTTO, PROFª., EMEI','gestor'),
    ('renatayaoita@educacao.pmrp.sp.gov.br','RENATA CAMPOS YAOITA','CARMEN APARECIDA DE CARVALHO RAMOS, EMEI','gestor'),
    ('carolinasantiago@educacao.pmrp.sp.gov.br','CAROLINA MAULIM E SILVA SANTIAGO','CECILIO FRAGUAS CEI','gestor'),
    ('egsilva@educacao.pmrp.sp.gov.br','EDIANA GOMES DA SILVA','CLORESDITH FERLIN FERREIRA CEI','gestor'),
    ('thaisbernardes@educacao.pmrp.sp.gov.br','THAIS HELENA PEREIRA BERNARDES','DEOLINDA GASPARINI CEI','gestor'),
    ('talesbastos@educacao.pmrp.sp.gov.br','TALES HENRIQUE MATOS BASTOS','DERCY CELIA SEIXAS FERRARI, PROFª., EMEF','gestor'),
    ('anselmobelan@educacao.pmrp.sp.gov.br','ANSELMO BELAN','DERCY CELIA SEIXAS FERRARI, PROFª., EMEF','gestor'),
    ('rogeriojesus@educacao.pmrp.sp.gov.br','ROGÉRIO GONÇALVES DE JESUS','DERCY CELIA SEIXAS FERRARI, PROFª., EMEF','coordenador'),
    ('carlaassis@educacao.pmrp.sp.gov.br','CARLA ALYRIA MARQUES ASSIS','DOM BOSCO CEI','gestor'),
    ('alexiasousa@educacao.pmrp.sp.gov.br','ALEXIA CRISTINA DE SOUSA','DOMINGOS ADILSON CANESIN, EMEF','gestor'),
    ('daianaanjos@educacao.pmrp.sp.gov.br','DAIANA APARECIDA GUIRALDELI DOS ANJOS','DOMINGOS ADILSON CANESIN, EMEF','gestor'),
    ('lisandralima@educacao.pmrp.sp.gov.br','LISANDRA PRISCILA RAVAGNOLI DE O.LIMA','DOMINGOS ADILSON CANESIN, EMEF','coordenador'),
    ('maristelazeviani@educacao.pmrp.sp.gov.br','MARISTELA ZEVIANI','DOMINGOS ANGERAMI, PROFº., EMEF','gestor'),
    ('dejaimeribeiro@educacao.pmrp.sp.gov.br','DEJAIME DE OLIVEIRA RIBEIRO','DOMINGOS ANGERAMI, PROFº., EMEF','gestor'),
    ('elainedorne@educacao.pmrp.sp.gov.br','ELAINE CAPRETZ BORGES DA SILVA DORNE','DR. CELSO CHARURI','gestor'),
    ('merciaferreira@educacao.pmrp.sp.gov.br','MERCIA DIANA COTA FERREIRA','EDUARDO ROMUALDO DE SOUZA, PROFº., EMEF','gestor'),
    ('joelmasouza@educacao.pmrp.sp.gov.br','JOELMA SOARES DE SOUZA','EDUARDO ROMUALDO DE SOUZA, PROFº., EMEF','gestor'),
    ('lucasrodrigues@educacao.pmrp.sp.gov.br','LUCAS TOUSO RODRIGUES','EGYDIO PEDRESCHI,CEEEF','gestor'),
    ('mariamoreira@educacao.pmrp.sp.gov.br','MARIA HELENA BIMBATTI','EGYDIO PEDRESCHI,CEEEF','coordenador'),
    ('zildacampanini@educacao.pmrp.sp.gov.br','ZILDA VIEIRA DOS SANTOS CAMPANINI','ELISA DUBOC GARCIA, PROFª., EMEF','gestor'),
    ('rejaneguimaraes@educacao.pmrp.sp.gov.br','REJANE TEODORO GUIMARÃES','ELISA DUBOC GARCIA, PROFª., EMEF','gestor'),
    ('ericleamartins@educacao.pmrp.sp.gov.br','ERICLEA REGIANE BESSA MARTINS','ELISA DUBOC GARCIA, PROFª., EMEF','coordenador'),
    ('shirleylemes@educacao.pmrp.sp.gov.br','SHIRLEY FABIANA PEREIRA LEMES','ELZA GUAZZELI DA COSTA, PROFª, EMEI','gestor'),
    ('sabrinasouza@educacao.pmrp.sp.gov.br','SABRINA CUSTODIO CORCINO DE SOUZA','EMILIO JARBINET, PADRE, EMEI','gestor'),
    ('giovannaoliveira@educacao.pmrp.sp.gov.br','GIOVANNA CRISTINA OLIVEIRA','ENEIDA PEREIRA DOS SANTOS AGUIAR, EMEF','gestor'),
    ('carmelitasimao@educacao.pmrp.sp.gov.br','CARMELITA DE AMORIM SIMAO DE ARAUJO','ENEIDA PEREIRA DOS SANTOS AGUIAR, EMEF','gestor'),
    ('pauladias@educacao.pmrp.sp.gov.br','PAULA REZENDE HAUTZ DIAS','ENEIDA PEREIRA DOS SANTOS AGUIAR, EMEF','coordenador'),
    ('silmarapestana@educacao.pmrp.sp.gov.br','SILMARA GONÇALVES PESTANA','EPONINA DE BRITTO ROSSETO, PROFª., EMEF','gestor'),
    ('marcelasouza@educacao.pmrp.sp.gov.br','MARCELA CASTRO DE SOUZA MAXIMINO','EPONINA DE BRITTO ROSSETO, PROFª., EMEF','gestor'),
    ('marinarosa@educacao.pmrp.sp.gov.br','MARINA ISRAEL DIAS ROSA','EPONINA DE BRITTO ROSSETO, PROFª., EMEF','coordenador'),
    ('germanotobias@educacao.pmrp.sp.gov.br','GERMANO DE JESUS TOBIAS','FAUSTINO JARRUCHE, EMEF','gestor'),
    ('katiagiannini@educacao.pmrp.sp.gov.br','KATIA MARIA GIANNINI','FAUSTINO JARRUCHE, EMEF','gestor'),
    ('silviaalves@educacao.pmrp.sp.gov.br','SILVIA HELENA SEIXAS ALVES','FAUSTINO JARRUCHE, EMEF','coordenador'),
    ('alexelias@educacao.pmrp.sp.gov.br','ALEX JULIANO LEMES RODRIGUES ELIAS','FELICITA DRUDI COSTA PINTO CEI','gestor'),
    ('andremartins@educacao.pmrp.sp.gov.br','ANDRE LUIS FERREIRA MARTINS','GERALDA DE SOUZA ESPIN, EMEF','gestor'),
    ('tainasouza@educacao.pmrp.sp.gov.br','TAINA JACOMINI DE SOUZA','GERALDA DE SOUZA ESPIN, EMEF','gestor'),
    ('raquelpedrozo@educacao.pmrp.sp.gov.br','RAQUEL CALDAS HAYAXIBARA PEDROZO','GIRASSOL ENCANTADO CEI','gestor'),
    ('vmsalves@educacao.pmrp.sp.gov.br','VERA MONICA SILVA ALVES','HENILLA GODOY VELLUDO SALVADOR, EMEI','gestor'),
    ('angelabispo@educacao.pmrp.sp.gov.br','ANGELA KATIA CIRIACO BISPO MELO','HILDA MARIA SOBRAL BARBOSA MANDARINO, EMEI','gestor'),
    ('ericasantos@educacao.pmrp.sp.gov.br','ERICA DINAH DE OLIVEIRA DOS SANTOS','HILDA MOSCA, EMEI','gestor'),
    ('michelemartins@educacao.pmrp.sp.gov.br','MICHELE ROCHA DE OLIVEIRA MARTINS','HONORATO DE LUCCA, PROFº., EMEF','gestor'),
    ('cleomaragarcia@educacao.pmrp.sp.gov.br','CLEOMARA APARECIDA GARCIA','HONORATO DE LUCCA, PROFº., EMEF','gestor'),
    ('marcelamarcantonio@educacao.pmrp.sp.gov.br','MARCELA SANCHES MARCANTONIO','HONORATO DE LUCCA, PROFº., EMEF','coordenador'),
    ('solangepereira@educacao.pmrp.sp.gov.br','SOLANGE CARACHO PEREIRA','HORTENCIO PEREIRA DA SILVA PROF CEI','gestor'),
    ('josemaravieira@educacao.pmrp.sp.gov.br','JOSEMARA DUARTE VIEIRA','IRIA JUNQUEIRA, DONA, EMEI','gestor'),
    ('humbertosouza@educacao.pmrp.sp.gov.br','HUMBERTO LUIZ GUIMARÃES DE SOUZA','JAIME MONTEIRO DE BARROS DR., EMEF','gestor'),
    ('suelivieira@educacao.pmrp.sp.gov.br','SUELI APARECIDA VIEIRA','JAIME MONTEIRO DE BARROS DR., EMEF','gestor'),
    ('simeisantos@educacao.pmrp.sp.gov.br','SIMEI DARIO VIANA DOS SANTOS','JARBAS MASSULO, PROFº., EMEF','gestor'),
    ('mariasantanna@educacao.pmrp.sp.gov.br','MARIA DAS GRAÇAS SANT´ANNA FERREIRA','JARBAS MASSULO, PROFº., EMEF','gestor'),
    ('andersonsilva@educacao.pmrp.sp.gov.br','ANDERSON TAVARES DA SILVA','JARBAS MASSULO, PROFº., EMEF','coordenador'),
    ('gracasouza@educacao.pmrp.sp.gov.br','GRAÇA DAIANE CARASSATO DE SOUZA','JESUS DE NAZARE CEI','gestor'),
    ('alinefroes@educacao.pmrp.sp.gov.br','ALINE BRUNA BARBOSA ARAUJO FROES','JOAO DA CRUZ MOREIRA CEI/EMEI','gestor'),
    ('amandabrito@educacao.pmrp.sp.gov.br','AMANDA FERNANDES BRITO','JOAO GILBERTO SAMPAIO, DR., EMEF','gestor'),
    ('marcelobernine@educacao.pmrp.sp.gov.br','MARCELO BERNINE','JOAO GILBERTO SAMPAIO, DR., EMEF','gestor'),
    ('marizetesantos@educacao.pmrp.sp.gov.br','MARIZETE PEREIRA DE JESUS SANTOS','JOAO GILBERTO SAMPAIO, DR., EMEF','coordenador'),
    ('thelmapeixoto@educacao.pmrp.sp.gov.br','THELMA DE LIMA PEIXOTO','JOAO PEDRO CASTROVIEJO CEI','gestor'),
    ('anapatricia@educacao.pmrp.sp.gov.br','ANA PATRICIA RIBEIRO DA SILVA','JOAO SPERANDIO, DEP., EMEI','gestor'),
    ('anabordonal@educacao.pmrp.sp.gov.br','ANA CLAUDIA BORDONAL','JOSE BONIFACIO COUTINHO NOGUEIRA, EMEI','gestor'),
    ('normapatriarcha@educacao.pmrp.sp.gov.br','NORMA DONIZETI ALVES PATRIARCHA','JOSE CARLOS SOBRAL, DR., EMEI','gestor'),
    ('vagnersilva@educacao.pmrp.sp.gov.br','VAGNER DUTRA DA SILVA','JOSE DELIBO, VER., EMEF','gestor'),
    ('lgouvea@educacao.pmrp.sp.gov.br','LARISSA CRISTINE GOUVEIA','JOSE DELIBO, VER., EMEF','gestor'),
    ('thaisbarbosa@educacao.pmrp.sp.gov.br','THAIS COUTINHO BARBOSA','JOSE PEDRO MOREIRA, PROFº., EMEI','gestor'),
    ('cintiasaab@educacao.pmrp.sp.gov.br','CINTIA DE CARVALHO VECHI SAAB','JOSE ROBERTO FELICIO, EMEI','gestor'),
    ('guilhermeferreira@educacao.pmrp.sp.gov.br','GUILHERME GONÇALVES FERREIRA DA SILVA','JOSE RODINI LUIZ PROFº., EMEF','gestor'),
    ('flaviaizippato@educacao.pmrp.sp.gov.br','FLAVIA JOISE IZIPPATO','JOSE RODINI LUIZ PROFº., EMEF','gestor'),
    ('monicamartins@educacao.pmrp.sp.gov.br','MONICA CAROLINA JURCA MARTINS','JOSE RODINI LUIZ PROFº., EMEF','coordenador'),
    ('ericksilva@educacao.pmrp.sp.gov.br','ERICK ROBERTO FREIRE DE ARAUJO SILVA','JULIO CESAR VOLTARELLI, EMEF','gestor'),
    ('ricardojunior@educacao.pmrp.sp.gov.br','RICARDO PAROLO JUNIOR','JULIO CESAR VOLTARELLI, EMEF','gestor'),
    ('leandrorodrigues@educacao.pmrp.sp.gov.br','LEANDRO LINO GONCALVES RODRIGUES','LAURIVALDO FIDELIS CEI','gestor'),
    ('rosanecintra@educacao.pmrp.sp.gov.br','ROSANE VICTORINO DA ROCHA CINTRA','LEONOR MERTÍLIA COSTA CEI','gestor'),
    ('leticiamedeiros@educacao.pmrp.sp.gov.br','LETICIA CORREA MEDEIROS','LILIAN SPADARO ROSA E SILVA, PROFª., EMEI','gestor'),
    ('vanessacrispim@educacao.pmrp.sp.gov.br','VANESSA RAMOS CRISPIM DOS SANTOS','LUCIO MENDES CEI','gestor'),
    ('carladesertoli@educacao.pmrp.sp.gov.br','CARLA ROBERTA DESERTOLI','LUIS DO AMARAL MOUSINHO, DOM, EMEF','gestor'),
    ('raphaelaraposo@educacao.pmrp.sp.gov.br','RAPHAELA HENRIQUES RAPOSO','LUIS DO AMARAL MOUSINHO, DOM, EMEF','gestor'),
    ('marceloanjos@educacao.pmrp.sp.gov.br','MARCELO FERREIRA DOS ANJOS','LUIS DO AMARAL MOUSINHO, DOM, EMEF','coordenador'),
    ('alineavila@educacao.pmrp.sp.gov.br','ALINE TORRIZELLA PERIGO AVILA','MARIA APPARECIDA BORGES DE OLIVEIRA BONINI, EMEI','gestor'),
    ('julianaleite@educacao.pmrp.sp.gov.br','JULIANA FERREIRA LEITE DA SILVA','MARIA DE LOURDES GULLACI LAGUNA PROFA CEI','gestor'),
    ('dianasantos@educacao.pmrp.sp.gov.br','DIANA FERNANDA VAZ DE MELO DOS SANTOS','MARIA GORETTI, SANTA, EMEI','gestor'),
    ('sergiogomes@educacao.pmrp.sp.gov.br','SERGIO EDUARDO GOMES DA SILVA','MARIA HELENA BRAGA MONTE SERRAT, EMEI','gestor'),
    ('ricardopereira@educacao.pmrp.sp.gov.br','RICARDO ALEXANDRE PEREIRA','MARIA IGNEZ LOPES ROSSI, PROFª., EMEF','gestor'),
    ('geisagoncalves@educacao.pmrp.sp.gov.br','GEISA GABRIELE SILVA MELO GONÇALVES','MARIA IGNEZ LOPES ROSSI, PROFª., EMEF','gestor'),
    ('alineulian@educacao.pmrp.sp.gov.br','ALINE SILVA ULIAN','MARIA IGNEZ LOPES ROSSI, PROFª., EMEF','coordenador'),
    ('geremiasrigobello@educacao.pmrp.sp.gov.br','GEREMIAS FRANCO CARNIEL RIGOBELLO','MARIA INES VIEIRA MACHADO, PROFª., EMEF','gestor'),
    ('anapdias@educacao.pmrp.sp.gov.br','ANA PAULA DIAS','MARIA INES VIEIRA MACHADO, PROFª., EMEF','gestor'),
    ('lilianmargatho@educacao.pmrp.sp.gov.br','LILIAN CRISTIANE MARGATHO PEREIRA','MARIA INES VIEIRA MACHADO, PROFª., EMEF','coordenador'),
    ('fernanda@educacao.pmrp.sp.gov.br','FERNANDA MARTINS PEREIRA','MARIA LUCIA MEIRELLES JUNQUEIRA CEI','gestor'),
    ('lucianaoliveira@educacao.pmrp.sp.gov.br','LUCIANA STELA DE OLIVEIRA','MARIA PONTIM, EMEI','gestor'),
    ('vivianeferro@educacao.pmrp.sp.gov.br','VIVIANE CARLA SCAGLIONI FERRO','MARIA REGINA CAVALCANTE PROFA CEI','gestor'),
    ('fmoura@educacao.pmrp.sp.gov.br','FLAVIA MARIANA FERNANDES DE MOURA','MARLENE JORGE DOS REIS, EMEI','gestor'),
    ('lucimarafarias@educacao.pmrp.sp.gov.br','LUCIMARA ALVES FARIAS','MARLENE MARREIRO SIBILLE CEI','gestor'),
    ('priscilacosta@educacao.pmrp.sp.gov.br','PRISCILA ANTUNES COSTA','MIGUEL MUSSI, EMEI','gestor'),
    ('danielereis@educacao.pmrp.sp.gov.br','DANIELE CANDIDA DA SILVA REIS','MOACIR FIRMINO, EMEI','gestor'),
    ('flaviapaula@educacao.pmrp.sp.gov.br','FLAVIA APARECIDA DE AVILA DE PAULA','MODELO MARINCEK CEI','gestor'),
    ('josianelucena@educacao.pmrp.sp.gov.br','JOSIANE RODRIGUES OLIVEIRA DE LUCENA','NAIR MANOELINA DE OLIVEIRA CEI','gestor'),
    ('selmavieira@educacao.pmrp.sp.gov.br','SELMA REGINA FURIO VIEIRA','NARCISO NICOLODI, IRMÃO, EMEI','gestor'),
    ('flaviachiaretti@educacao.pmrp.sp.gov.br','FLAVIA TAMBURUS CHIARETTI','NEIDE APPARECIDA GOLFETTO DE CASTRO, EMEI','gestor'),
    ('liaferreira@educacao.pmrp.sp.gov.br','LIA CINTHIA FERREIRA','NELSON COSTA DOS SANTOS PADRE CEI','gestor'),
    ('marcianovato@educacao.pmrp.sp.gov.br','MARCIA APARECIDA NOVATO DE SOUSA','NELSON MACHADO, EMEF','gestor'),
    ('gislainepereira@educacao.pmrp.sp.gov.br','GISLAINE ANDREA PEREIRA','NELSON MACHADO, EMEF','gestor'),
    ('suelileite@educacao.pmrp.sp.gov.br','SUELI LEITE','NELSON MACHADO, EMEF','coordenador'),
    ('analeme@educacao.pmrp.sp.gov.br','ANA PAULA PAES LEME','NEUZA MICHELUTTI MARZOLA, PROFª., EMEF','gestor'),
    ('leandromorais@educacao.pmrp.sp.gov.br','LEANDRO RODRIGUES MORAIS','NEUZA MICHELUTTI MARZOLA, PROFª., EMEF','gestor'),
    ('alinepratali@educacao.pmrp.sp.gov.br','ALINE PRATALI RIBEIRO','NICOLAU DINAMARCO SPINELLI, DR., EMEI','gestor'),
    ('larissatrindade@educacao.pmrp.sp.gov.br','LARISSA APARECIDA TRINDADE','OPUS DEI CEI','gestor'),
    ('anneliseleite@educacao.pmrp.sp.gov.br','ANNELISE SIMARI CARREIRA LEITE','PAULO FREIRE, PROFº., EMEF','gestor'),
    ('melinaagostini@educacao.pmrp.sp.gov.br','MELINA MACHADO AGOSTINI','PAULO FREIRE, PROFº., EMEF','gestor'),
    ('alanbarbosa@educacao.pmrp.sp.gov.br','ALAN DE MARCO BARBOSA','PAULO FREIRE, PROFº., EMEF','coordenador'),
    ('lucienisouza@educacao.pmrp.sp.gov.br','LUCIENI REGIANI DA SILVA DE SOUZA','PAULO HENRIQUE DE SOUZA, EMEI','gestor'),
    ('donizetibarbosa@educacao.pmrp.sp.gov.br','DONIZETI APARECIDO BARBOSA','PAULO MONTE SERRAT FILHO, PROFº., DR., EMEF','gestor'),
    ('marciapaiva@educacao.pmrp.sp.gov.br','MARCIA DE PAIVA RAMOS','PAULO MONTE SERRAT FILHO, PROFº., DR., EMEF','gestor'),
    ('amandaaraujo@educacao.pmrp.sp.gov.br','AMANDA LOPES DA SILVA ARAUJO','PAULO MONTE SERRAT FILHO, PROFº., DR., EMEF','coordenador'),
    ('rosangelasilveira@educacao.pmrp.sp.gov.br','ROSANGELA LAGO SILVEIRA','QUINTINO VIEIRA CEI','gestor'),
    ('mauricioneto@educacao.pmrp.sp.gov.br','MAURICIO ORTIZ NETO','RAUL MACHADO, PROFº., EMEF','gestor'),
    ('vanessadeluca@educacao.pmrp.sp.gov.br','VANESSA DE LUCA','RAUL MACHADO, PROFº., EMEF','gestor'),
    ('suelipereira@educacao.pmrp.sp.gov.br','SUELI DE ARAUJO PEREIRA','RAUL MACHADO, PROFº., EMEF','coordenador'),
    ('paulatoffani@educacao.pmrp.sp.gov.br','PAULA TOFFANI EICHENBERGER','RENATO CAMARGO MENDES CEI','gestor'),
    ('mariliaaliarde@educacao.pmrp.sp.gov.br','MARILIA ALIARDE','ROBERTO AFONSO PONTES, EMEI','gestor'),
    ('adrianacsilva@educacao.pmrp.sp.gov.br','ADRIANA CUNHA PEREIRA DA SILVA','ROBERTO TARANTO CEI','gestor'),
    ('andressasilva@educacao.pmrp.sp.gov.br','ANDRESSA MARQUES FORTE SILVA','ROSA MARIA DE BRITTO COSENZA CEI','gestor'),
    ('cjunior@educacao.pmrp.sp.gov.br','CASSIO ROBERTO GONZALES JUNIOR','RUY ESCOREL FERREIRA SANTOS, EMEI','gestor'),
    ('miriandaniel@educacao.pmrp.sp.gov.br','MIRIAN QUEIROZ DE SOUZA DANIEL','SALVADOR MARTURANO, PROFº., EMEF','gestor'),
    ('paulafonseca@educacao.pmrp.sp.gov.br','PAULA LETÍCIA FONSECA','SALVADOR MARTURANO, PROFº., EMEF','gestor'),
    ('soniamuniz@educacao.pmrp.sp.gov.br','SONIA REGINA MORAES DE MELLO','SEBASTIAO DE AGUIAR AZEVEDO, EMEF','gestor'),
    ('mariahipolito@educacao.pmrp.sp.gov.br','MARIA LUIZA MARTINS FERREIRA HIPOLITO','SEBASTIAO DE AGUIAR AZEVEDO, EMEF','coordenador'),
    ('analandi@educacao.pmrp.sp.gov.br','ANA LUISA LANDI','SEBASTIAO DE AGUIAR AZEVEDO, EMEF - UN. II','gestor'),
    ('amandacordeiro@educacao.pmrp.sp.gov.br','AMANDA CORDEIRO DOS SANTOS','SEBASTIAO MARTINS DE MOURA CEI','gestor'),
    ('gislainemartoni@educacao.pmrp.sp.gov.br','GISLAINE CRISTINA CECILIO MARTONI','TERESA HENDRICA ANTONISSEN, EMEI','gestor'),
    ('patricialeite@educacao.pmrp.sp.gov.br','PATRICIA ALVES RODRIGUES LEITE','TEREZINHA, SANTA, EMEI','gestor'),
    ('gustavosoares@educacao.pmrp.sp.gov.br','GUSTAVO KAIQUE SOARES','THOMAZ URBINATTI CEI','gestor'),
    ('karenramalho@educacao.pmrp.sp.gov.br','KAREN CRISTINA SECCO RAMALHO','TONY MIYASAKA CEI','gestor'),
    ('belguermacarini@educacao.pmrp.sp.gov.br','BELGUER WICLES MACARINI','VIRGILIO SALATA, EMEF','gestor'),
    ('carolinebarbosa@educacao.pmrp.sp.gov.br','CAROLINE BARRETO BRUNELLI BARBOSA','VIRGILIO SALATA, EMEF','gestor'),
    ('mmiranda@educacao.pmrp.sp.gov.br','MARIA APARECIDA MIRANDA','VIRGILIO SALATA, EMEF','coordenador'),
    ('idaletesilva@educacao.pmrp.sp.gov.br','IDALETE DA SILVA','VITOR YUSSEF DARKOUBI CEI','gestor'),
    ('snunes@educacao.pmrp.sp.gov.br','SANDRA PAES LEME NUNES','WALDEMAR ROBERTO, PROF.,DR., EMEF','gestor'),
    ('joaocarneiro@educacao.pmrp.sp.gov.br','JOAO ROGERIO CARNEIRO','WALDEMAR ROBERTO, PROF.,DR., EMEF','gestor'),
    ('juliopironi@educacao.pmrp.sp.gov.br','JULIO CESAR PIRONI','WALDEMAR ROBERTO, PROF.,DR., EMEF','coordenador'),
    ('elianaoctavio@educacao.pmrp.sp.gov.br','ELIANA CARLA DE SOUZA OCTAVIO','WANDA PRINCIVALLI MARCAL, EMEI','gestor'),
    ('dejanepaulino@educacao.pmrp.sp.gov.br','DEJANE DE ALMEIDA PAULINO','WILSON ROSELINO, EMEI','gestor'),
    ('josebincoleto@educacao.pmrp.sp.gov.br','JOSE EDUARDO LEITE BINCOLETO','ZILDA COSSA D AVILA, EMEI','gestor');

-- 1) Garante uma escola para cada unidade citada (casando por nome normalizado).
insert into public.escolas (nome)
select distinct i.escola from _imp i
where not exists (select 1 from public.escolas e
                  where public.norm_escola(e.nome) = public.norm_escola(i.escola));

-- 2) Cria os perfis (não sobrescreve quem já existe).
insert into public.perfis (email, nome, tipo, ativo)
select lower(i.email), max(i.nome), 'escola', true
from _imp i
group by lower(i.email)
on conflict (email) do nothing;

-- 3) Vincula cada perfil à sua unidade.
insert into public.perfil_escola (perfil_id, escola_id, vinculo)
select distinct p.id, e.id, i.vinculo
from _imp i
join public.perfis  p on p.email = lower(i.email)
join public.escolas e on public.norm_escola(e.nome) = public.norm_escola(i.escola)
on conflict (perfil_id, escola_id) do nothing;

drop table _imp;

-- Conferência:
-- select count(*) from public.perfis where tipo='escola';
